import type { Metadata } from "next"

import { Inter } from "next/font/google"

import AppLayout from "@/layouts/AppLayout"

import "./globals.scss"

const inter = Inter({
   subsets: ["latin"],
   display: "swap",
   weight: ["400", "700"],
   variable: "--font-inter",
})

export const metadata: Metadata = {
   title: "LafiaEMR Authentication",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <AppLayout>{children}</AppLayout>
         </body>
      </html>
   )
}
