import type { Metadata } from "next"

import AppLayout from "@/layouts/AppLayout"

import "./globals.scss"

export const metadata: Metadata = {
   title: "LafiaEMR Authentication",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body>
            <AppLayout>{children}</AppLayout>
         </body>
      </html>
   )
}
